# Generated by Django 3.2 on 2022-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220816_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPost',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
